import Head from 'next/head';
import Image from 'next/image';
import {
  AcademicCap,
  CalculatorIcon,
  ChipIcon,
  CodeBracket,
  CodeForces,
  ComputerIcon,
  DBIcon,
  GithubIcon,
  HackerRank,
  LeetCodeIcon,
  LocationIcon,
  ServerIcon,
} from '@/components/Icons';
import { useState } from 'react';
import Link from 'next/link';

function Hero() {
  const [translateX, setTranslateX] = useState(0);
  const [translateY, setTranslateY] = useState(0);

  const handleMouseMove = (event: React.MouseEvent) => {
    const { clientX, clientY } = event;
    const centerX = window.innerWidth / 2;
    const centerY = window.innerHeight / 2;
    const deltaX = clientX - centerX;
    const deltaY = clientY - centerY;
    const translateX = deltaX * 0.05;
    const translateY = deltaY * 0.05;
    setTranslateX(translateX);
    setTranslateY(translateY);
  };

  return (
    <>
      <Head>
        <title>MD Pabel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='relative flex flex-col items-center justify-center w-full overflow-visible text-center'>
        <h1 className='inline-block text-transparent bg-clip-text font-bold text-5xl md:text-7xl tracking-[-1.25px] black-gradient'>
          Hi, I&#x27;m Pabel.
        </h1>
        <div className='flex justify-center my-6 space-x-2 font-medium text-paragraph'>
          <LocationIcon />
          <div className=''>Cumilla, BD</div>
        </div>
        <div className='flex justify-center w-full'>
          <div className='max-w-lg mx-8 space-x-2 paragraphSize md:mx-auto text-paragraph'>
            I&#x27;m a recent computer science graduate and I&#x27;m excited to
            pursue my passion for creating engaging digital experiences.
            <AcademicCap />
          </div>
        </div>
        {/* <div
          onMouseMove={handleMouseMove}
          className='absolute w-full md:w-[800px] h-[320px] -top-[108x] px-8'
        >
          <ChipIcon
            style={{
              transform: `translate3d(${translateX}px, ${translateY}px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute md:top-0 w-[17px] h-[17px] text-gray-700 opacity-70'
          />
          <ServerIcon
            style={{
              transform: `translate3d(${translateX * 1.2}px, ${
                translateY * 1.2
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute text-gray-700 top-10 right-5 md:right-10'
          />
          <DBIcon
            style={{
              transform: `translate3d(${translateX * 1.4}px, ${
                translateY * 1.4
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute w-[32px] h-[32px] text-gray-700 top-1/3 left-5 md:left-32 opacity-40'
          />
          <CodeBracket
            style={{
              transform: `translate3d(${translateX * 1.6}px, ${
                translateY * 1.6
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute w-[18px] h-[18px] md:top-32 top-1/2 left-2/3 md:left-2/3 text-gray-700 opacity-60'
          />
          <ComputerIcon
            style={{
              transform: `translate3d(${translateX * 1.8}px, ${
                translateY * 1.8
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute bottom-0 w-[15px]  text-gray-700'
          />
          <CalculatorIcon
            style={{
              transform: `translate3d(${translateX * 2}px, ${
                translateY * 2
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute right-5 md:right-0 w-[16px] h-[16px] bottom-2 md:bottom-20 text-gray-800 opacity-80'
          />
          <ChipIcon
            style={{
              transform: `translate3d(${translateX * 1.6}px, ${
                translateY * 1.6
              }px, 0) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-26deg) skew(0deg, 0deg)`,
            }}
            className='absolute bottom-0 w-[32px] h-[32px] text-gray-700 opacity-50 left-1/2 md:left-2/3'
          />
        </div> */}

        <div className='flex gap-6 pt-10'>
          <Link target='_blank' href='https://leetcode.com/mdpabel/'>
            <LeetCodeIcon />
          </Link>
          <Link target='_blank' href='https://github.com/mdpabel'>
            <GithubIcon />
          </Link>
          <Link target='_blank' href='https://www.hackerrank.com/mdpabel385'>
            <HackerRank />
          </Link>
          <Link target='_blank' href='https://codeforces.com/profile/MD_Pabel'>
            <CodeForces />
          </Link>
        </div>
      </div>
    </>
  );
}

export default Hero;
