import Head from 'next/head';
import Image from 'next/image';
import {
  AcademicCap,
  CalculatorIcon,
  ChipIcon,
  CodeBracket,
  CodeForces,
  ComputerIcon,
  CVIcon,
  DBIcon,
  GithubIcon,
  HackerRank,
  LeetCodeIcon,
  LocationIcon,
  ServerIcon,
} from '@/components/Icons';
import cvIcon from '../assets/cvicon.png';
import { useState } from 'react';
import Link from 'next/link';

function Hero() {
  const [translateX, setTranslateX] = useState(0);
  const [translateY, setTranslateY] = useState(0);

  const handleMouseMove = (event: React.MouseEvent) => {
    const { clientX, clientY } = event;
    const centerX = window.innerWidth / 2;
    const centerY = window.innerHeight / 2;
    const deltaX = clientX - centerX;
    const deltaY = clientY - centerY;
    const translateX = deltaX * 0.05;
    const translateY = deltaY * 0.05;
    setTranslateX(translateX);
    setTranslateY(translateY);
  };

  return (
    <>
      <Head>
        <title>MD Pabel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='relative flex flex-col items-center justify-center w-full overflow-visible text-center'>
        <h1 className='inline-block text-transparent bg-clip-text font-bold text-5xl md:text-7xl tracking-[-1.25px] black-gradient'>
          Hi, I&#x27;m Pabel.
        </h1>
        <div className='flex justify-center my-6 space-x-2 font-medium text-paragraph'>
          <LocationIcon />
          <div className=''>Cumilla, BD</div>
        </div>
        <div className='flex justify-center w-full'>
          <div className='max-w-lg mx-8 space-x-2 paragraphSize md:mx-auto text-paragraph'>
            I&#x27;m a recent computer science graduate and I&#x27;m excited to
            pursue my passion for creating engaging digital experiences.
            <AcademicCap />
          </div>
        </div>
        <div className='flex gap-6 pt-10'>
          <Link
            aria-label='leetcode profile'
            target='_blank'
            href='https://leetcode.com/mdpabel/'
          >
            <LeetCodeIcon />
          </Link>
          <Link
            aria-label='github profile'
            target='_blank'
            href='https://github.com/mdpabel'
          >
            <GithubIcon />
          </Link>
          <Link
            aria-label='hackerrank profile'
            target='_blank'
            href='https://www.hackerrank.com/mdpabel385'
          >
            <HackerRank />
          </Link>
          {/* <Link target='_blank' href='https://codeforces.com/profile/MD_Pabel'>
            <CodeForces />
          </Link> */}
          <Link
            aria-label='Open Resume'
            target='_blank'
            href='https://drive.google.com/file/d/1A6I4qF3WBwlKskaAT23G5volEAJ-9i4T/view'
          >
            {/* <Image src={cvIcon} alt='CV Icon' width={24} height={24} /> */}
            <CVIcon />
          </Link>
        </div>
      </div>
    </>
  );
}

export default Hero;
